- name: Setup NodeJs repo
  shell: curl -sL https://rpm.nodesource.com/setup_16.x | bash -

- name: Install dependencies
  ansible.builtin.yum:
    name:
      - unzip
      - nodejs
    state: present
