- name: vars on play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Variable from file in play level
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Task level variables
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: task.example.com

- name: variable from inventory
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
       msg: URL == {{URL}}
