- name: when git download is defined
  block:
   - name: Download and unzip the application content
     ansible.builtin.unarchive:
       src: https://github.com/udayayeswar/app/archive/main.zip
       dest: /tmp
       remote_src: yes
