- name: Download and unzip the application content
  ansible.builtin.unarchive:
    src: https://github.com/udayayeswar/app/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy app content
  ansible.builtin.copy:
    src: /tmp/app-main/
    dest: /home/{{USER}}/{{COMPONENT}}/
    remote_src: yes
  become_user: "{{USER}}"

- name: Install packages based on package.json.
  shell: npm install
  args:
    chdir: "/home/{{USER}}/{{COMPONENT}}"
  become_user: "{{USER}}"
