- name: Install EPEL repository
  become: yes
  become_method: sudo
  yum:
    name: epel-release
    state: present

- name: Install Nginx is Install
  ansible.builtin.yum:
    name:
      - nginx
    state: present

- name: download application data
  import_tasks: download.yml